### ISSUE TITLE
Last version CDN for this module

### ISSUE THREAD

**Issue by ppKrauss** [w8r/GreinerHormann#15]
Hi, I see there are [a CDN at cdn.rawgit.com](https://cdn.rawgit.com/w8r/GreinerHormann/aa0b660a/dist/greiner-hormann.leaflet.min.js), but it is not updated.. There are a newer one?

**Comment by w8r** [comment]
[this one](https://cdn.rawgit.com/w8r/GreinerHormann/482ad4/dist/greiner-hormann.leaflet.min.js), or you can get any of them from [https://unpkg.com/greiner-hormann](https://unpkg.com/greiner-hormann)
