### ISSUE TITLE
Intersection makes no sense to me.

### ISSUE THREAD

**Issue by JamesNewton** [w8r/GreinerHormann#16]
````
var greinerHormann = require('greiner-hormann');
var intersection = greinerHormann.intersection([[1,1],[2,1],[2,2],[2,1],[1,1]], [[1,1],[3,2],[2,2],[2,1],[1,1]]);
var out = []
if(intersection){
    if(typeof intersection[0][0] === 'number'){ 
        out = [intersection]
        console.log("single linear ring")
    }
    console.log("length:"+intersection.length)
    for(var i = 0, len = intersection.length; i < len; i++){
        out.push([intersection[i]])
    }
} else {console.log("no intersection")}
console.log("output"+out)
````

Gives:
length:1
output2,1.5,2,1,1,1,1,1,2,1,2,2,2,1.5

????

**Comment by w8r** [comment]
The shapes you've provided make little sense, too. They have collapsed edges. What is the source of those?

**Comment by JamesNewton** [comment]
So the issue is that I don't understand the required format for polygons. And have no clue what collapsed edges are or how to avoid them. I was just assuming you provide a set of 2d points, in this case, they describe the corner of a rectangle and the other is a rectangle with one point moved out of place.  So e.g. `[[1,1],[2,1],[2,2],[2,1],[1,1]]` is "start at x=1, y=1. Move to x=2, y=1" and so on through x2y2, x2y1, and finally return to x1y1. 

Can you point me at how polygons should be defined?

**Comment by JamesNewton** [comment]
Ah, nevermind, I see it. The points [2,1] and [2,1] repeated... The second one should be 1,2.
