### ISSUE TITLE
Is there a subtract method?

### ISSUE THREAD

**Issue by army8735** [w8r/GreinerHormann#20]
Only intersection, union, difference

**Comment by army8735** [comment]
It seems that greinerHormann.diff() = polygonA - polygonB.

miss difference(xor)?

![image](https://user-images.githubusercontent.com/174904/104830792-19cf2080-58bd-11eb-93ad-005af99f1fff.png)

**Comment by w8r** [comment]
I suggest you to use [w8r/martinez](https://github.com/w8r/martinez/) instead

**Comment by army8735** [comment]
Wow, working with self-intersecting polygons and degenerate polygons!
thanks.
