### ISSUE TITLE
O(n^2)

### ISSUE THREAD

**Issue by theKashey** [w8r/GreinerHormann#5]
Polygon.clip method has n^2 complexity.
Try https://en.wikipedia.org/wiki/Bentley–Ottmann_algorithm or linear quad tree(via Z code), as earcut do.

**Comment by w8r** [comment]
I have my eyes on a different one these days)) And Greiner-Hormann is just really beautiful.

**Comment by theKashey** [comment]
I am only about moment of finding intersections. Not further operations.

**Comment by w8r** [comment]
You mean replacing the first stage of the algorithm with bentley-ottmann? There is a paper on this extension of the algorithm if I'm not mistaken. Could be done, but it doesn't solve the problem of degeneracies of this one. And all the attempts to solve it make the algorithm uglier. I will publish another one when I'm ready

**Comment by theKashey** [comment]
To say the truth - bentley-ottmann is about self-intercections (btw – you do not handle them) and just about speed.
Anyway polygonal clipping in realtime is not a good idea.

**Comment by w8r** [comment]
> self-intercections (btw – you do not handle them)

That's the best part about Greiner-Hormann - [it handles them by default](https://jsfiddle.net/w8r/yzt31s4b/)

But as I said, your suggestion is really good and can speed up that algorithm, another one I'm working on is using sweeping line + a variation of the graph-walking approach of GH

**Comment by theKashey** [comment]
It works fine with two polygons. Not with one.
http://jsfiddle.net/93pszmph/

**Comment by theKashey** [comment]
It use some variation of https://en.wikipedia.org/wiki/Weiler–Atherton_clipping_algorithm
Works simple – on intersection choose left or right (way). Left (cross(v1,v2)==sin) leads to outer contour and will join two poly. Right leads to xor.

**Comment by w8r** [comment]
for O(nlogn) algorithm look at https://github.com/w8r/martinez
